#!/usr/bin/env python3
"""Generate worker/src/gemeinden-list.js with the allowlist of valid gemeinde slugs.

The Cloudflare Worker uses this list to distinguish valid gemeinde subdomains
(redirect to /gemeinden/<slug>/) from unknown ones (redirect to apex).

Source of truth: the directories under gemeinden/ (generated by generate_gemeinden.py).
"""

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
GEMEINDEN_DIR = ROOT / 'gemeinden'
OUT_FILE = ROOT / 'worker' / 'src' / 'gemeinden-list.js'


def collect_slugs() -> list[str]:
    if not GEMEINDEN_DIR.is_dir():
        return []
    return sorted([
        d.name for d in GEMEINDEN_DIR.iterdir()
        if d.is_dir() and (d / 'index.html').is_file()
    ])


def main():
    slugs = collect_slugs()
    content = (
        "// AUTO-GENERATED by generate_worker_gemeinden.py — DO NOT EDIT MANUALLY\n"
        "// Source: gemeinden/ directories (regenerated by rebuild.py)\n"
        "\n"
        f"export const GEMEINDE_SLUGS = new Set({json.dumps(slugs, indent=2, ensure_ascii=False)});\n"
    )
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(content, encoding='utf-8')
    print(f"Wrote {OUT_FILE.relative_to(ROOT)} with {len(slugs)} slug(s)")


if __name__ == '__main__':
    main()
